# Generated by Django 3.1.2 on 2020-10-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('tipo_mascota', models.CharField(max_length=100)),
                ('raza_mascota', models.CharField(max_length=100)),
                ('descripcion_mascota', models.CharField(max_length=300)),
                ('codigo_qr', models.CharField(max_length=100)),
                ('foto_mascota', models.ImageField(upload_to=None)),
                ('in_home', models.BooleanField(default=False)),
                ('id_usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
