# Generated by Django 3.1.2 on 2020-10-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201023_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto_mascota',
            field=models.ImageField(upload_to='api/resources/mascotas'),
        ),
    ]
