# Generated by Django 3.1.2 on 2020-10-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201028_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota_encontrada',
            fields=[
                ('id_mascota_encontrada', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'mascota_encontrada',
            },
        ),
        migrations.CreateModel(
            name='Mascota_perdida',
            fields=[
                ('id_mascota_perdida', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'mascota_perdida',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('fecha_reporte', models.CharField(max_length=100)),
                ('descripcion_reporte', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='Reporte_avistado',
            fields=[
                ('id_reporte_avistado', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('lugar_avistado', models.CharField(max_length=100)),
                ('imagen_avistamiento', models.ImageField(blank=True, upload_to='api/resources/mascotas')),
            ],
            options={
                'verbose_name_plural': 'reporte_avistado',
            },
        ),
        migrations.CreateModel(
            name='Reporte_encontrado',
            fields=[
                ('id_reporte_encontrado', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('lugar_encontrado', models.CharField(max_length=100)),
                ('imagen_encontrado', models.ImageField(blank=True, upload_to='api/resources/mascotas')),
                ('mascota_recojida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'reporte_encontrado',
            },
        ),
        migrations.CreateModel(
            name='Reporte_perdido',
            fields=[
                ('id_reporte_perdido', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('ultimo_lugar_visto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'reporte_perdido',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('correo_duenio', models.CharField(max_length=100)),
                ('nombre_duenio', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'usuario',
            },
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name_plural': 'mascota'},
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='mascota',
            name='id_mascota',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
