# Generated by Django 3.1.2 on 2020-10-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201028_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.usuario', verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='mascota_encontrada',
            name='id_mascota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.mascota', verbose_name='mascota'),
        ),
        migrations.AddField(
            model_name='mascota_perdida',
            name='id_mascota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.mascota', verbose_name='mascota'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='id_mascota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.mascota', verbose_name='mascota'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.usuario', verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='reporte_avistado',
            name='id_reporte',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.reporte', verbose_name='reporte'),
        ),
        migrations.AddField(
            model_name='reporte_encontrado',
            name='id_reporte',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.reporte', verbose_name='reporte'),
        ),
        migrations.AddField(
            model_name='reporte_perdido',
            name='id_reporte',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.reporte', verbose_name='reporte'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_reporte',
            field=models.DateField(),
        ),
    ]
