# Generated by Django 3.1.2 on 2020-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201028_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='id_mascota',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='reporte_avistado',
            name='id_reporte',
        ),
        migrations.RemoveField(
            model_name='reporte_encontrado',
            name='id_reporte',
        ),
        migrations.RemoveField(
            model_name='reporte_perdido',
            name='id_reporte',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_duenio',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
