# Generated by Django 3.1.2 on 2020-10-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201028_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='id_mascota',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.mascota', verbose_name='mascota'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='usuario'),
        ),
    ]
