# Generated by Django 3.1.2 on 2020-10-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201028_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte_avistado',
            name='id_reporte',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.reporte', verbose_name='reporte'),
        ),
        migrations.AddField(
            model_name='reporte_encontrado',
            name='id_reporte',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.reporte', verbose_name='reporte'),
        ),
        migrations.AddField(
            model_name='reporte_perdido',
            name='id_reporte',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.reporte', verbose_name='reporte'),
        ),
    ]
