# Generated by Django 3.1.2 on 2020-10-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201028_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_duenio',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
