# Generated by Django 3.1.2 on 2020-10-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201028_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id_mascota',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mascota_encontrada',
            name='id_mascota_encontrada',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mascota_perdida',
            name='id_mascota_perdida',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='id_reporte',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reporte_avistado',
            name='id_reporte_avistado',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reporte_encontrado',
            name='id_reporte_encontrado',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reporte_perdido',
            name='id_reporte_perdido',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
