# Generated by Django 3.1.2 on 2020-11-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201028_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='mascota_encontrada',
            name='id_mascota',
            field=models.ForeignKey(db_column='id_mascota', default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.mascota', verbose_name='mascota'),
        ),
        migrations.AlterField(
            model_name='mascota_perdida',
            name='id_mascota',
            field=models.ForeignKey(db_column='id_mascota', default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.mascota', verbose_name='mascota'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='id_mascota',
            field=models.ForeignKey(db_column='id_mascota', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.mascota', verbose_name='mascota'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to='api.usuario', verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='reporte_avistado',
            name='id_reporte',
            field=models.ForeignKey(db_column='id_reporte', default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.reporte', verbose_name='reporte'),
        ),
        migrations.AlterField(
            model_name='reporte_encontrado',
            name='id_reporte',
            field=models.ForeignKey(db_column='id_reporte', default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.reporte', verbose_name='reporte'),
        ),
        migrations.AlterField(
            model_name='reporte_perdido',
            name='id_reporte',
            field=models.ForeignKey(db_column='id_reporte', default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.reporte', verbose_name='reporte'),
        ),
    ]
